-- MySQL Script generated by MySQL Workbench
-- 08/23/18 23:37:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema commuteaid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema commuteaid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `commuteaid` DEFAULT CHARACTER SET utf8 ;
USE `commuteaid` ;

-- -----------------------------------------------------
-- Table `commuteaid`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commuteaid`.`route` (
  `id` INT NOT NULL,
  `origin` VARCHAR(45) NULL,
  `drop_off` VARCHAR(45) NULL,
  `eta` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuteaid`.`commuter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commuteaid`.`commuter` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `authkey` VARCHAR(45) NULL,
  `password_hash` VARCHAR(45) NULL,
  `password_reset_token` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `route_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_route1_idx` (`route_id` ASC),
  CONSTRAINT `fk_user_route1`
    FOREIGN KEY (`route_id`)
    REFERENCES `commuteaid`.`route` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuteaid`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commuteaid`.`vehicle` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `plate_number` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `route_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicle_route1_idx` (`route_id` ASC),
  CONSTRAINT `fk_vehicle_route1`
    FOREIGN KEY (`route_id`)
    REFERENCES `commuteaid`.`route` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuteaid`.`seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commuteaid`.`seat` (
  `id` INT NOT NULL,
  `seat_number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuteaid`.`vehicle_seat_reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commuteaid`.`vehicle_seat_reservation` (
  `vehicle_id` INT NOT NULL,
  `seat_reservation_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `time_start` TIME NULL,
  `time_end` TIME NULL,
  `date` DATE NULL,
  `remarks` VARCHAR(45) NULL,
  PRIMARY KEY (`vehicle_id`, `seat_reservation_id`),
  INDEX `fk_vehicle_has_seat_reservation_seat_reservation1_idx` (`seat_reservation_id` ASC),
  INDEX `fk_vehicle_has_seat_reservation_vehicle_idx` (`vehicle_id` ASC),
  INDEX `fk_vehicle_has_seat_reservation_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_vehicle_has_seat_reservation_vehicle`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `commuteaid`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_has_seat_reservation_seat_reservation1`
    FOREIGN KEY (`seat_reservation_id`)
    REFERENCES `commuteaid`.`seat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_has_seat_reservation_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `commuteaid`.`commuter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuteaid`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commuteaid`.`rating` (
  `id` INT NOT NULL,
  `rating_number` VARCHAR(45) NULL,
  `route_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rating_route1_idx` (`route_id` ASC),
  CONSTRAINT `fk_rating_route1`
    FOREIGN KEY (`route_id`)
    REFERENCES `commuteaid`.`route` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuteaid`.`poll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commuteaid`.`poll` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `question` VARCHAR(45) NULL,
  `options` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_poll_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_poll_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `commuteaid`.`commuter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
